name = "Tutanota"
description = "Tutanota is the old name of Tuta — a freemium secure email provider."
hostnames = [ "tutanota.com", "tutao.de" ]
slug = "tutanota"
parent = "tuta"
contributors = [ "doamatto" ]